/*
SQLyog Community v13.1.5  (64 bit)
MySQL - 5.5.62 : Database - hotal
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`hotal` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE `hotal`;

/*Table structure for table `hotal` */

DROP TABLE IF EXISTS `hotal`;

CREATE TABLE `hotal` (
  `ID` int(100) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `CITY` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `TOTAL_ROOM` int(100) NOT NULL DEFAULT '0',
  `NUMBER_OF_STAR` int(10) DEFAULT NULL,
  `WIFI` tinyint(4) DEFAULT NULL,
  `RESTAURANT` tinyint(4) DEFAULT NULL,
  `AIR_CONDITION` tinyint(10) DEFAULT NULL,
  `COST_OF_STAY` int(100) NOT NULL DEFAULT '1',
  `IS_ACTIVE` tinyint(1) DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL,
  `CREATED_ON` date DEFAULT NULL,
  `DATE` date DEFAULT NULL,
  `AVAILABLITY` tinyint(2) DEFAULT '0',
  `NUMBER_OF_BOOKED_ROOM` int(100) NOT NULL DEFAULT '0',
  `REVIEW` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `AVAILABLE_ROOM` int(100) NOT NULL DEFAULT '0',
  `RENTED_ROOM` int(100) NOT NULL DEFAULT '0',
  `RATING` int(100) NOT NULL DEFAULT '0',
  `COST_OF_SINGLE_ROOM` int(100) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*Data for the table `hotal` */

insert  into `hotal`(`ID`,`NAME`,`CITY`,`TOTAL_ROOM`,`NUMBER_OF_STAR`,`WIFI`,`RESTAURANT`,`AIR_CONDITION`,`COST_OF_STAY`,`IS_ACTIVE`,`IS_DELETED`,`CREATED_ON`,`DATE`,`AVAILABLITY`,`NUMBER_OF_BOOKED_ROOM`,`REVIEW`,`AVAILABLE_ROOM`,`RENTED_ROOM`,`RATING`,`COST_OF_SINGLE_ROOM`) values 
(2,'Radha','Bad',200,12,1,1,1,0,1,0,'2022-10-11','2022-10-11',1,0,NULL,0,0,10,150),
(3,'rerere','Bad',200,12,1,1,1,0,1,0,'2022-10-11',NULL,1,0,NULL,0,0,11,200);

/*Table structure for table `review` */

DROP TABLE IF EXISTS `review`;

CREATE TABLE `review` (
  `ID` int(100) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(100) NOT NULL DEFAULT '0',
  `COMMENTS` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `RATINGS` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `HOTAL_ID` int(100) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*Data for the table `review` */

insert  into `review`(`ID`,`USER_ID`,`COMMENTS`,`RATINGS`,`NAME`,`HOTAL_ID`) values 
(2,12,'good','3',NULL,1),
(3,0,'Bad','3',NULL,2),
(4,0,'Bad','3',NULL,2);

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `ID` int(100) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `LAST_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `MOBILE_NUMBER` varchar(14) COLLATE utf8_bin DEFAULT NULL,
  `AADHAR_NUMBER` varchar(15) COLLATE utf8_bin DEFAULT NULL,
  `HOTAL_ID` int(10) NOT NULL DEFAULT '0',
  `IS_ACTIVE` tinyint(1) DEFAULT NULL,
  `IS_DELETED` tinyint(1) DEFAULT NULL,
  `CREATED_ON` date DEFAULT NULL,
  `HOTAL_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

/*Data for the table `user` */

insert  into `user`(`ID`,`FIRST_NAME`,`LAST_NAME`,`MOBILE_NUMBER`,`AADHAR_NUMBER`,`HOTAL_ID`,`IS_ACTIVE`,`IS_DELETED`,`CREATED_ON`,`HOTAL_NAME`) values 
(1,'Ram','Kumar','232323','23323',122,1,1,'2022-10-08',NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
